services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - '3000:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    stdin_open: true

  backend:
    build: 
      context: ./Talkathon
      dockerfile: Talkathon/Dockerfile
    ports: 
      - 8080:80